---
- name: Fetch disk utilization from Linux EC2 instances
  hosts: linux_ec2
  gather_facts: no
  tasks:
    - name: Check disk space utilization
      shell: df -h --output=source,size,used,avail,pcent
      register: disk_usage

    - name: Save output to JSON
      copy:
        content: "{{ disk_usage.stdout }}"
        dest: "/tmp/disk_usage_{{ inventory_hostname }}.json"

    - name: Upload JSON to S3
      aws_s3:
        bucket: "disk-usage-data"
        object: "disk_usage/{{ inventory_hostname }}.json"
        src: "/tmp/disk_usage_{{ inventory_hostname }}.json"
        mode: put
        region: "us-east-1"
      delegate_to: localhost
